# Generated by Django 5.2.6 on 2025-10-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactmessage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/WhatsApp')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('DESIGN', 'Design e Diagramação'), ('CAPAS', 'Criação de Capas'), ('PRODUCAO', 'Produção e Acabamento')], default='DESIGN', max_length=100, verbose_name='Título do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Estimado (R$)')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_album', models.CharField(max_length=150, verbose_name='Nome do Álbum/Evento')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início do Projeto')),
                ('prazo_estimado', models.PositiveIntegerField(verbose_name='Prazo Estimado (dias)')),
                ('capa_imagem', models.ImageField(blank=True, null=True, upload_to='projetos/capas/', verbose_name='Capa do Álbum')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('D', 'Em Diagramação'), ('A', 'Aprovado'), ('E', 'Em Encadernação'), ('F', 'Finalizado')], default='P', max_length=1, verbose_name='Status do Projeto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='core.cliente', verbose_name='Cliente')),
                ('servicos_contratados', models.ManyToManyField(related_name='projetos', to='core.servico', verbose_name='Serviços Contratados')),
            ],
            options={
                'verbose_name': 'Projeto/Álbum',
                'verbose_name_plural': 'Projetos/Álbuns',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
