# Generated by Django 5.2.6 on 2025-10-15 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_depoimento_delete_testimonial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Transformo suas memórias em álbuns que contam histórias', max_length=255, verbose_name='Título Principal (Hero)')),
                ('hero_lead', models.TextField(default='Com foco em design autêntico e acabamento premium...', verbose_name='Subtítulo (Lead Hero)')),
                ('about_title', models.CharField(default='José Pedro - O Designer', max_length=150, verbose_name='Título Sobre Mim')),
                ('about_text_p1', models.TextField(default='Olá! Sou José Pedro, designer de álbuns...', verbose_name='Parágrafo 1 (Sobre Mim)')),
                ('about_text_p2', models.TextField(blank=True, default='Minha paixão é transformar fotos em histórias visuais...', null=True, verbose_name='Parágrafo 2 (Sobre Mim)')),
                ('whatsapp_number', models.CharField(default='(74) 9924-8931', max_length=20, verbose_name='Número do WhatsApp')),
                ('email_address', models.EmailField(default='zepedro.contato@gmail.com', max_length=254, verbose_name='Endereço de E-mail')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Site',
                'verbose_name_plural': 'Configuração Geral do Site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.CharField(max_length=200, verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='Depoimento',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='servicos_contratados',
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='projeto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Designer/Responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='capa_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/capas/', verbose_name='Capa Imagem'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome_album',
            field=models.CharField(max_length=200, verbose_name='Nome do Álbum'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo_estimado',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo Estimado (Entrega)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('REVISAO', 'Em Revisão'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=50, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
