# Generated by Django 5.2.6 on 2025-10-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfig_testimonial_alter_projeto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto/Álbum', 'verbose_name_plural': 'Projetos/Álbuns'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Imagem da Seção Sobre Mim'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Imagem Principal (Hero)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text_p1',
            field=models.TextField(default='Designer profissional focado em criar narrativas visuais únicas...', verbose_name='Parágrafo 1 (Sobre Mim)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text_p2',
            field=models.TextField(blank=True, help_text='Segundo parágrafo (Opcional)', null=True, verbose_name='Parágrafo 2 (Sobre Mim)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_title',
            field=models.CharField(default='José Pedro - O Designer de Álbums', max_length=150, verbose_name='Título Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_lead',
            field=models.TextField(default='Com foco em design autêntico e acabamento premium, crio álbuns que eternizam momentos.', verbose_name='Subtítulo (Lead Hero)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='Transformo suas memórias em álbuns que contam histórias', max_length=200, verbose_name='Título Principal (Hero)'),
        ),
    ]
