# Generated by Django 5.2.6 on 2025-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projeto_options_siteconfig_about_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['status', 'prazo_estimado'], 'verbose_name': 'Projeto de Álbum', 'verbose_name_plural': 'Projetos de Álbum'},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_image',
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text_p1',
            field=models.TextField(default='Primeiro parágrafo do texto sobre o designer.', verbose_name='Parágrafo 1 do Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text_p2',
            field=models.TextField(default='Segundo parágrafo do texto sobre o designer.', verbose_name='Parágrafo 2 do Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_title',
            field=models.CharField(default='Sobre Mim', max_length=150, verbose_name='Título da Seção Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_lead',
            field=models.TextField(default='Com foco em design autêntico e acabamento premium, crio álbuns que eternizam momentos.', verbose_name='Texto de Introdução (Lead)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='Transformo suas memórias em álbuns que contam histórias', max_length=255, verbose_name='Título da Seção Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(default='(74) 9924-8931', max_length=20, verbose_name='Número de WhatsApp'),
        ),
    ]
