# Generated by Django 5.2.6 on 2025-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_projeto_options_remove_projeto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_curta',
            field=models.CharField(default='', help_text='Texto curto que aparece logo abaixo do título na Home.', max_length=255, verbose_name='Descrição do Card'),
            preserve_default=False,
        ),
    ]
