# Generated by Django 5.2.6 on 2025-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projeto_options_projeto_descricao_curta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
