# Generated by Django 5.2.6 on 2025-10-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactmessage_city_contactmessage_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.AlterField(
            model_name='projeto',
            name='capa_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo_estimado',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo estimado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text_p1',
            field=models.TextField(blank=True, verbose_name='Parágrafo 1'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text_p2',
            field=models.TextField(blank=True, verbose_name='Parágrafo 2'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_title',
            field=models.CharField(max_length=255, verbose_name='Título Sobre'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_lead',
            field=models.TextField(blank=True, verbose_name='Texto Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(max_length=255, verbose_name='Título Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
