# Generated by Django 5.2.6 on 2025-10-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_siteconfig_options_alter_projeto_capa_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Classe de Ícone CSS (Ex: fas fa-camera)')),
            ],
            options={
                'verbose_name': 'Serviço/Pacote',
                'verbose_name_plural': 'Serviços/Pacotes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='servicos_incluidos',
            field=models.ManyToManyField(related_name='projetos', to='core.servico', verbose_name='Serviços Incluídos'),
        ),
    ]
